Traceback (most recent call last):
  File "/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brunamoura/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df_eventos_apos2022 = df_eventos.copy()

df_eventos_apos2022 = df_eventos_apos2022.dropna(subset=['PIB'])
#Existem dados para o PIB apenas at√© 2022.

df_eventos_apos2022['PIB_per_capita'] = df_eventos_apos2022['PIB'] / df_eventos_apos2022['Pop']

plt.figure(figsize=(10, 6))
sns.boxplot(x='Status', y='PIB_per_capita', data=df_eventos_apos2022, palette='deep', order=status_counts.index)
plt.title('Distribui√ß√£o da renda per capita por status de reconhecimento')
plt.xlabel('Status')
plt.ylabel('Renda per capita')
plt.xticks(rotation=0)
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 9[0m
[1;32m      6[0m df_eventos_apos2022[[38;5;124m'[39m[38;5;124mPIB_per_capita[39m[38;5;124m'[39m] [38;5;241m=[39m df_eventos_apos2022[[38;5;124m'[39m[38;5;124mPIB[39m[38;5;124m'[39m] [38;5;241m/[39m df_eventos_apos2022[[38;5;124m'[39m[38;5;124mPop[39m[38;5;124m'[39m]
[1;32m      8[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m10[39m, [38;5;241m6[39m))
[0;32m----> 9[0m sns[38;5;241m.[39mboxplot(x[38;5;241m=[39m[38;5;124m'[39m[38;5;124mStatus[39m[38;5;124m'[39m, y[38;5;241m=[39m[38;5;124m'[39m[38;5;124mPIB_per_capita[39m[38;5;124m'[39m, data[38;5;241m=[39mdf_eventos_apos2022, palette[38;5;241m=[39m[38;5;124m'[39m[38;5;124mdeep[39m[38;5;124m'[39m, order[38;5;241m=[39m[43mstatus_counts[49m[38;5;241m.[39mindex)
[1;32m     10[0m plt[38;5;241m.[39mtitle([38;5;124m'[39m[38;5;124mDistribui√ß√£o da renda per capita por status de reconhecimento[39m[38;5;124m'[39m)
[1;32m     11[0m plt[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124mStatus[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'status_counts' is not defined

